version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12.0
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: houses
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
